version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: postgres_db_fastapi
    restart: unless-stopped
    environment:
      POSTGRES_DB: prometheus-metrics-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
